# Generated by Django 4.2.2 on 2023-07-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=500)),
                ("implementing_agency", models.CharField(max_length=200)),
                (
                    "technology_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("capacity", models.CharField(blank=True, max_length=20, null=True)),
                ("project_code", models.IntegerField(blank=True, null=True)),
                (
                    "start_date",
                    models.DateField(
                        blank=True, default="1900-01-01", max_length=20, null=True
                    ),
                ),
                (
                    "completion_date",
                    models.DateField(
                        blank=True, default="3000-01-01", max_length=20, null=True
                    ),
                ),
                (
                    "budget",
                    models.CharField(
                        blank=True, default="N/A", max_length=20, null=True
                    ),
                ),
                (
                    "division",
                    models.CharField(
                        blank=True, default="N/A", max_length=20, null=True
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, default="N/A", max_length=20, null=True
                    ),
                ),
                (
                    "upazilla",
                    models.CharField(
                        blank=True, default="N/A", max_length=20, null=True
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, default="N/A", max_length=100, null=True
                    ),
                ),
                (
                    "latitude",
                    models.CharField(
                        blank=True, default="N/A", max_length=30, null=True
                    ),
                ),
                (
                    "longitude",
                    models.CharField(
                        blank=True, default="N/A", max_length=30, null=True
                    ),
                ),
                (
                    "grid_status",
                    models.CharField(
                        blank=True, default="N/A", max_length=100, null=True
                    ),
                ),
                (
                    "present_status",
                    models.CharField(
                        blank=True, default="N/A", max_length=60, null=True
                    ),
                ),
                ("note", models.TextField(blank=True, default="N/A", null=True)),
                (
                    "expected_life_time",
                    models.CharField(
                        blank=True, default="N/A", max_length=50, null=True
                    ),
                ),
                (
                    "expected_till_now",
                    models.CharField(
                        blank=True, default="N/A", max_length=50, null=True
                    ),
                ),
                (
                    "pd_name",
                    models.CharField(
                        blank=True, default="N/A", max_length=30, null=True
                    ),
                ),
                (
                    "date_of_approval",
                    models.CharField(
                        blank=True, default="N/A", max_length=15, null=True
                    ),
                ),
                (
                    "cumulative_expenditure",
                    models.CharField(
                        blank=True, default="N/A", max_length=50, null=True
                    ),
                ),
                (
                    "physical_progress",
                    models.CharField(
                        blank=True, default="N/A", max_length=5, null=True
                    ),
                ),
                (
                    "short_title",
                    models.CharField(
                        blank=True, default="N/A", max_length=20, null=True
                    ),
                ),
                (
                    "approval_ref",
                    models.CharField(
                        blank=True, default="N/A", max_length=10, null=True
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        blank=True, default="N/A", max_length=25, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, default="N/A", max_length=100, null=True
                    ),
                ),
                (
                    "funded_by",
                    models.CharField(
                        blank=True, default="N/A", max_length=30, null=True
                    ),
                ),
                (
                    "image",
                    models.CharField(
                        blank=True, default="N/A", max_length=150, null=True
                    ),
                ),
                (
                    "progress_reporting_date",
                    models.CharField(
                        blank=True, default="N/A", max_length=15, null=True
                    ),
                ),
                (
                    "ministry",
                    models.CharField(
                        blank=True, default="N/A", max_length=50, null=True
                    ),
                ),
                (
                    "executing_agency",
                    models.CharField(
                        blank=True, default="N/A", max_length=50, null=True
                    ),
                ),
                ("category", models.CharField(max_length=200)),
            ],
        ),
    ]
