# Generated by Django 4.2.2 on 2023-07-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="capacity",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="technology_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
