# Generated by Django 4.2.2 on 2023-07-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo_app", "0003_alter_project_project_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.CharField(
                blank=True, default="N/A", max_length=150, null=True
            ),
        ),
    ]
