# Generated by Django 4.2.2 on 2023-07-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo_app", "0004_alter_project_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="completion_date",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
