# Generated by Django 4.2.2 on 2023-07-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo_app", "0005_alter_project_completion_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="completion_date",
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="cumulative_expenditure",
            field=models.CharField(blank=True, default="N/A", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
    ]
