# Generated by Django 4.2.2 on 2023-07-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo_app", "0006_alter_project_completion_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(
                blank=True, default="1900-01-01", max_length=20, null=True
            ),
        ),
    ]
