# Generated by Django 4.2.2 on 2023-07-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo_app", "0007_alter_project_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="grid_status",
            field=models.CharField(
                blank=True, default="N/A", max_length=100, null=True
            ),
        ),
    ]
