# Generated by Django 4.2.2 on 2023-07-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("name", models.CharField(max_length=22, verbose_name="Name")),
                (
                    "email",
                    models.EmailField(
                        max_length=50, unique=True, verbose_name="Email Address"
                    ),
                ),
                (
                    "user_role",
                    models.CharField(
                        choices=[
                            ("System Admin", "System Admin"),
                            (
                                "Executive Committee of the National Economic Council",
                                "Executive Committee of the National Economic Council",
                            ),
                            ("Ministry of Planning", "Ministry of Planning"),
                            ("Executing Agency", "Executing Agency"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="User Role",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_SYSADMIN", models.BooleanField(default=False)),
                ("is_ECNEC", models.BooleanField(default=False)),
                ("is_MOP", models.BooleanField(default=False)),
                ("is_EXEC", models.BooleanField(default=False)),
                ("is_appuser", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
